<?php
include __DIR__ . '/include/head.phtml';
?>
<main class="container py-4">
    <h2>Contato</h2>
    <p>Esta é a página de contato. Entre em contato conosco através do email</p>
    <form action="" method="get">
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" class="form-control" id="email" name="email" required>
        </div>
        <div>
            <label for="phone">Telefone:</label>
            <input type="tel" class="form-control" id="phone" name="phone" required>
        </div>
        <div class="form-group">
            <label for="message">Mensagem:</label>
            <textarea class="form-control" id="message" name="message" rows="5" required></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Enviar</button>
    </form>
</main>
<?php include __DIR__ . '/include/footer.phtml'; ?>