<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title ?></title>
    <link rel="stylesheet" href="styles.css">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/styles/app.css">
</head>

<body>
    <header>
        <h1>Produtos de Sacanagem</h1>
    </header>
    <nav class="nav-wrapper">
        <a href="/">Home</a>
        <a href="/products">Produtos</a>
        <a href="/contact">Contato</a>
    </nav>